// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package main

import (
	"github.com/go-kratos/kratos/v2"
	"github.com/go-kratos/kratos/v2/log"
	"scrm/app/auth/service/internal/biz"
	"scrm/app/auth/service/internal/conf"
	"scrm/app/auth/service/internal/data"
	"scrm/app/auth/service/internal/server"
	"scrm/app/auth/service/internal/service"
)

// Injectors from wire.go:

// initApp init kratos application.
func initApp(confServer *conf.Server, registry *conf.Registry, confData *conf.Data, logger log.Logger) (*kratos.App, func(), error) {
	db := data.NewDB(confData, logger)
	dataData, cleanup, err := data.NewData(db, logger)
	if err != nil {
		return nil, nil, err
	}
	authRepo := data.NewAuthRepo(dataData, logger)
	authUseCase := biz.NewAuthUseCase(authRepo, logger)
	authService := service.NewAuthService(authUseCase)
	grpcServer := server.NewGRPCServer(confServer, logger, authService)
	registrar := server.NewEtcdRegistrar(registry)
	app := newApp(logger, grpcServer, registrar)
	return app, func() {
		cleanup()
	}, nil
}
